#spring.application.name=Backend
#spring.datasource.url=jdbc:mysql://localhost:3306/Althura?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
#spring.datasource.username=root
#spring.datasource.password=root123
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=false
#spring.jpa.open-in-view=false
#logging.level.org.springframework.security=INFO
#spring.jpa.properties.hibernate.jdbc.time_zone=UTC
#
#server.port=8080
#
#ispshoes.app.jwtSecret=AlturaShoeStoreSecretKeyForJwtAuthenticationWhichShouldBeAtLeast256BitsLong2026
#ispshoes.app.jwtExpirationMs=86400000


spring.application.name=Backend
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/test?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
logging.level.org.springframework.security=INFO
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

server.port=8080

ispshoes.app.jwtSecret=AlturaShoeStoreSecretKeyForJwtAuthenticationWhichShouldBeAtLeast256BitsLong2026
ispshoes.app.jwtExpirationMs=86400000